export const MENSAJES = {
  exceso: [
    "Vas muy rápido, la próxima toma un taxi",
    "¿A dónde vas tan rápido? ¿Al hospital? Porque así vas a llegar",
    "El límite es sugerencia para todos, menos para ti al parecer",
    "Tu seguro de vida te manda saludos",
    "Los semáforos en rojo también aplican para ti, por si no lo sabías",
    "Velocidad detectada. Dignidad, cuestionada",
    "¿Sabías que las multas también van rápido? Más que tú",
    "El velocímetro no miente. Tú sí",
    "Manejando así vas a llegar primero... a la multa de tránsito",
    "Tranquilo, la calle no se va a mover",
    "¿Estás huyendo de algo o simplemente eres así?",
    "GPS dice: reduce la velocidad. Tú dices: no. GPS insiste",
    "El carro de adelante también tiene prisa, pero él respeta los límites",
    "Conductor detectado en modo videojuego",
    "Vas tan rápido que el viento está asustado",
    "Reducir velocidad no te hace menos nada",
    "Bonito carro para manejarlo así",
    "Las cámaras de fotomulta también van a 0 km/h. Espérate",
    "Si llegas 3 minutos tarde, el problema no es la velocidad",
    "Velocidad de videojuego, consecuencias de la vida real",
  ],
  perfecto: [
    "Sabemos que es más lento de lo que manejas, pero está bien",
    "Tu abuela estaría orgullosa",
    "Así se maneja, campeón",
    "Hoy no hay multas. Hoy ganaste",
    "¿Ves? No duele respetar los límites",
    "Llevas un rato bien. Nosotros lo notamos aunque nadie más lo haga",
    "Conductor ejemplar detectado. Evento poco frecuente",
    "Si todos manejaran como tú, habría menos accidentes y menos dramas",
    "Tranquilo, el destino te espera. No tiene para dónde irse",
    "Esto es lo que se siente manejar sin adrenalina innecesaria",
    "Modo zen activado. Sigue así",
    "Los pasajeros imaginarios en tu carro están cómodos",
    "Velocidad correcta, karma en verde",
    "Hoy no eres un peligro público. Eso cuenta",
    "Tu historial de conductor está brillando ahora mismo",
    "Slow and steady no solo gana la carrera, también la vida",
    "Semáforo en verde, velocidad en verde, vida en verde",
    "Así se llega al destino: aburrido pero vivo",
    "Récord personal de buen comportamiento en camino",
    "Si betterDriver tuviera estrellas Michelin, hoy te daríamos una",
  ],
  frenada: [
    "¿Olvidaste los frenos o los encontraste de golpe?",
    "Los frenos agradecen el ejercicio, pero no tanto",
    "Eso fue un frenón o un susto disfrazado de maniobra",
    "El café del copiloto ya está en el tablero",
    "Frenada detectada. Corazón del pasajero, también",
    "¿Viste algo o simplemente quisiste despertar a todos?",
    "Los frenos son para usarlos gradualmente, no de emergencia",
    "Nivel de susto en el carro: alto",
    "El cinturón hizo su trabajo. Tú no tanto",
    "Próxima vez frena antes, no durante",
    "Eso no fue frenar, eso fue rezar con los pies",
    "El ABS te salvó. Tú no te lo mereces todavía",
    "Conducción suave incluye frenar suave. Por si acaso",
    "Ese frenón tiene nombre y apellido: distracción",
    "Tu cuello llamó, dice que no está contento",
    "Frenada digna de película de acción. Pero esto no es película",
    "El semáforo lo viste, ¿verdad? Solo confirmando",
    "Freno de pánico detectado",
    "Eso se llama frenazo. En betterDriver lo llamamos oportunidad de mejorar",
    "Los pasajeros llegaron. El susto también",
  ],
  aceleracion: [
    "¿Esto es un carro o un cohete?",
    "Arrancaste como si la luz verde fuera personal",
    "Las llantas no te hicieron nada, ¿por qué las castigas?",
    "Arranque detectado. Elegancia, no tanto",
    "¿Prisa o simplemente así eres?",
    "El motor te lo agradece. Las llantas, no",
    "Aceleración brusca: el deporte favorito de los impacientes",
    "Saliste disparado. ¿A dónde ibas tan urgente?",
    "Modo Fast and Furious activado. betterDriver lo desaprueba",
    "La gasolina también tiene sentimientos",
    "Arranque suave, llegada segura. Arranque brusco, llegada igual pero con más drama",
    "¿Eso fue necesario? Retórico",
    "El carro de al lado no es tu competencia",
    "Arrancaste como si debieras plata",
    "Ese arranque consumió más gasolina de la que crees",
    "¿Semáforo en verde o bandera de carreras? Parece que lo segundo",
    "Aceleración registrada. Puntos, reducidos",
    "Saliste tan rápido que el espejo retrovisor no te alcanzó a ver",
    "La calle no es un autódromo",
    "Arrancaste bien... para una película de acción",
  ],
,
  aleatorio: [
    'Vas bien, la abuela está tranquila',
    'Así se maneja, sin dramas',
    '¿Ves? No duele respetar los límites',
    'El destino te espera, no tiene para dónde irse',
    'Velocidad correcta, karma en verde',
    'Sin multas, sin sustos, sin dramas',
    'La carretera es de todos, no solo tuya',
    'Hoy no eres un peligro público. Eso cuenta',
    'Modo zen activado',
    'Tu seguro de vida no tiene que trabajar hoy',
    'Así se llega: aburrido pero vivo',
    'La prisa es enemiga del buen conductor',
    'Cada semáforo en rojo es una oportunidad de respirar',
    'Llevas un rato bien. Nosotros lo notamos',
    'El carro de adelante también tiene prisa. Y también respeta los límites',
    'Sin infracciones por ahora. Sigue así',
    'Buen ritmo, conductor',
    'Hoy tu historial de conductor está limpio',
    'La abuela aprobaría esta conducción',
    'Velocidad normal, corazón tranquilo',
  ],
};

export function mensajeAleatorio(categoria: keyof typeof MENSAJES): string {
  const lista = MENSAJES[categoria];
  return lista[Math.floor(Math.random() * lista.length)];
}
